### ISSUE TITLE
Meta issue example

### ISSUE THREAD

**Issue by audrow** [audrow/gazebo-test-cases#1552]
- [ ] [Ubuntu Focal, Binary](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22) <-- This is the only combination that has had issues made for it
  - [ ] [docs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:docs)
  - [ ] [garden](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:garden)
  - [ ] [gz-common](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-common)
  - [ ] [gz-fuel-tools](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-fuel-tools)
  - [ ] [gz-gui](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-gui)
  - [ ] [gz-launch](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-launch)
  - [ ] [gz-math](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-math)
  - [ ] [gz-msgs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-msgs)
  - [ ] [gz-physics](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-physics)
  - [ ] [gz-plugin](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-plugin)
  - [ ] [gz-rendering](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-rendering)
  - [ ] [gz-sensors](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-sensors)
  - [ ] [gz-sim](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-sim)
  - [ ] [sdf worlds](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:sdf%20worlds)
  - [ ] [gz-tools](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-tools)
  - [ ] [gz-transport](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-transport)
  - [ ] [gz-utils](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:gz-utils)
  - [ ] [sdf_tutorials](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:sdf_tutorials)
  - [ ] [sdformat](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Binary%22+label:%22generation-1%22+label:sdformat)
- [ ] [Ubuntu Jammy, Binary](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22)
  - [ ] [docs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:docs)
  - [ ] [garden](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:garden)
  - [ ] [gz-common](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:gz-common)
  - [ ] [gz-fuel-tools](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:gz-fuel-tools)
  - [ ] [gz-gui](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:gz-gui)
  - [ ] [gz-launch](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Binary%22+label:%22generation-1%22+label:gz-launch)
  - [ ] [gz-math](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+…es?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Source%22+label:%22generation-1%22+label:sdf_tutorials)
  - [ ] [sdformat](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Focal%22+label:%22Source%22+label:%22generation-1%22+label:sdformat)
- [ ] [Ubuntu Jammy, Source](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22)
  - [ ] [docs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:docs)
  - [ ] [garden](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:garden)
  - [ ] [gz-common](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-common)
  - [ ] [gz-fuel-tools](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-fuel-tools)
  - [ ] [gz-gui](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-gui)
  - [ ] [gz-launch](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-launch)
  - [ ] [gz-math](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-math)
  - [ ] [gz-msgs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-msgs)
  - [ ] [gz-physics](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-physics)
  - [ ] [gz-plugin](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-plugin)
  - [ ] [gz-rendering](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-rendering)
  - [ ] [gz-sensors](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-sensors)
  - [ ] [gz-sim](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-sim)
  - [ ] [sdf worlds](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:sdf%20worlds)
  - [ ] [gz-tools](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-tools)
  - [ ] [gz-transport](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-transport)
  - [ ] [gz-utils](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:gz-utils)
  - [ ] [sdf_tutorials](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:sdf_tutorials)
  - [ ] [sdformat](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Ubuntu%20Jammy%22+label:%22Source%22+label:%22generation-1%22+label:sdformat)
- [ ] [macOS 11 (Big Sur), Source](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22macOS%2011%20(Big%20Sur)%22+label:%22Source%22+label:%22generation-1%22)
  - [ ] [docs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22macOS%2011%20(Big%20Sur)%22+label:%22Source%22+label:%22generation-1%22+label:docs)
  - [ ] [garden](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22macOS%2011%20(Big%20Sur)%22+label:%22Source%22+label:%22generation-1%22+label:garden)
- [ ] [Windows 10, Source](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Windows%2010%22+label:%22Source%22+label:%22generation-1%22)
  - [ ] [docs](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Windows%2010%22+label:%22Source%22+label:%22generation-1%22+label:docs)
  - [ ] [garden](https://github.com/audrow/gazebo-test-cases/issues?q=is%3Aissue+is%3Aopen+label:%22Windows%2010%22+label:%22Source%22+label:%22generation-1%22+label:garden)
